import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  ads: [
    {
      name: "house",
      slug: "house",
      category: "Ads",
      image: "/images/house.jpg",
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner1.jpg",
      id: 1,
    },
    {
      name: "camera",
      slug: "camera",
      category: "Ads",
      image: "/images/camera.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,

      banner: "/images/banner2.jpg",
    },
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 20,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      alt: "Golf pants",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      alt: "Fit pants",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      alt: "Classic pants",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      alt: "Free shirt",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      alt: "Fit shirt",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      alt: "Slim shirt",
      price: 20,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      alt: "Golf pants",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      alt: "Fit pants",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      alt: "Classic pants",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Smart TV",
      slug: "smart-tv",
      category: "Electronics",
      image: "/images/tv.jpg",
      alt: "Smart TV",
      price: 899,
      brand: "Sony",
      rating: 4.5,
      numReviews: 120,
      countInStock: 10,
      description:
        "A high-definition smart TV with built-in streaming capabilities.",
    },

    {
      name: "Denim Jacket",
      slug: "denim-jacket",
      category: "Clothing",
      image: "/images/jacket.jpg",
      alt: "Denim jacket",
      price: 59.99,
      brand: "Levi's",
      rating: 4.2,
      numReviews: 80,
      countInStock: 15,
      description: "A stylish and durable denim jacket for everyday wear.",
    },

    {
      name: "The Great Gatsby",
      slug: "the-great-gatsby",
      category: "Books",
      image: "/images/gatsby.jpg",
      alt: "The Great Gatsby book",
      price: 12.99,
      brand: "Penguin Books",
      rating: 4.8,
      numReviews: 200,
      countInStock: 5,
      description:
        "F. Scott Fitzgerald's classic novel depicting the Jazz Age in America.",
    },

    {
      name: "Wireless Headphones",
      slug: "wireless-headphones",
      category: "Electronics",
      image: "/images/headphones.jpg",
      alt: "Wireless headphones",
      price: 129.99,
      brand: "Bose",
      rating: 4.7,
      numReviews: 250,
      countInStock: 30,
      description:
        "High-quality wireless headphones with noise-canceling technology.",
    },

    {
      name: "Striped T-Shirt",
      slug: "striped-t-shirt",
      category: "Clothing",
      image: "/images/tshirt.jpg",
      alt: "Striped t-shirt",
      price: 19.99,
      brand: "H&M",
      rating: 3.9,
      numReviews: 65,
      countInStock: 25,
      description:
        "A comfortable and fashionable striped t-shirt for casual occasions.",
    },

    {
      name: "To Kill a Mockingbird",
      slug: "to-kill-a-mockingbird",
      category: "Books",
      image: "/images/mockingbird.jpg",
      alt: "To Kill a Mockingbird book",
      price: 10.99,
      brand: "Harper Collins",
      rating: 4.6,
      numReviews: 180,
      countInStock: 8,
      description:
        "Harper Lee's classic novel exploring racial injustice in the Deep South.",
    },

    {
      name: "Digital Camera",
      slug: "digital-camera",
      category: "Electronics",
      image: "/images/camera.jpg",
      alt: "Digital camera",
      price: 349.99,
      brand: "Canon",
      rating: 4.4,
      numReviews: 150,
      countInStock: 12,
      description:
        "A feature-rich digital camera for capturing high-quality photos and videos.",
    },

    {
      name: "Leather Boots",
      slug: "leather-boots",
      category: "Clothing",
      image: "/images/boots.jpg",
      alt: "Leather boots",
      price: 129.99,
      brand: "Timberland",
      rating: 4.3,
      numReviews: 95,
      countInStock: 18,
      description: "Stylish and durable leather boots for all-season wear.",
    },

    {
      name: "The Lord of the Rings",
      slug: "the-lord-of-the-rings",
      category: "Books",
      image: "/images/lotr.jpg",
      alt: "The Lord of the Rings book",
      price: 29.99,
      brand: "Houghton Mifflin Harcourt",
      rating: 4.9,
      numReviews: 300,
      countInStock: 3,
      description: "J.R.R. Tolkien's epic fantasy trilogy set in Middle-earth.",
    },

    {
      name: "Smartphone",
      slug: "smartphone",
      category: "Electronics",
      image: "/images/phone.jpg",
      alt: "Smartphone",
      price: 799.99,
      brand: "Apple",
      rating: 4.8,
      numReviews: 500,
      countInStock: 20,
      description:
        "A cutting-edge smartphone with advanced features and a sleek design.",
    },

    {
      name: "Summer Dress",
      slug: "summer-dress",
      category: "Clothing",
      image: "/images/dress.jpg",
      alt: "Summer dress",
      price: 39.99,
      brand: "Zara",
      rating: 4.1,
      numReviews: 75,
      countInStock: 30,
      description:
        "A lightweight and stylish dress perfect for the summer season.",
    },

    {
      name: "1984",
      slug: "1984",
      category: "Books",
      image: "/images/1984.jpg",
      alt: "1984 book",
      price: 14.99,
      brand: "Penguin Books",
      rating: 4.7,
      numReviews: 220,
      countInStock: 7,
      description:
        "George Orwell's dystopian novel exploring themes of totalitarianism and surveillance.",
    },

    {
      name: "Wireless Earbuds",
      slug: "wireless-earbuds",
      category: "Electronics",
      image: "/images/earbuds.jpg",
      alt: "Wireless earbuds",
      price: 89.99,
      brand: "JBL",
      rating: 4.3,
      numReviews: 180,
      countInStock: 25,
      description:
        "True wireless earbuds with excellent sound quality and long battery life.",
    },

    {
      name: "Hooded Sweatshirt",
      slug: "hooded-sweatshirt",
      category: "Clothing",
      image: "/images/hoodie.jpg",
      alt: "Hooded sweatshirt",
      price: 49.99,
      brand: "Nike",
      rating: 4.6,
      numReviews: 150,
      countInStock: 15,
      description:
        "A comfortable and trendy hooded sweatshirt for a casual sporty look.",
    },

    {
      name: "Pride and Prejudice",
      slug: "pride-and-prejudice",
      category: "Books",
      image: "/images/pride-prejudice.jpg",
      alt: "Pride and Prejudice book",
      price: 11.99,
      brand: "Penguin Books",
      rating: 4.8,
      numReviews: 250,
      countInStock: 5,
      description:
        "Jane Austen's beloved novel exploring love, class, and societal norms.",
    },

    {
      name: "Gaming Console",
      slug: "gaming-console",
      category: "Electronics",
      image: "/images/console.jpg",
      alt: "Gaming console",
      price: 399.99,
      brand: "Sony",
      rating: 4.9,
      numReviews: 350,
      countInStock: 8,
      description:
        "A powerful gaming console for immersive gaming experiences.",
    },

    {
      name: "Sunglasses",
      slug: "sunglasses",
      category: "Clothing",
      image: "/images/sunglasses.jpg",
      alt: "Sunglasses",
      price: 29.99,
      brand: "Ray-Ban",
      rating: 4.7,
      numReviews: 120,
      countInStock: 20,
      description:
        "Stylish sunglasses that provide both UV protection and a fashionable look.",
    },

    {
      name: "The Catcher in the Rye",
      slug: "the-catcher-in-the-rye",
      category: "Books",
      image: "/images/catcher-rye.jpg",
      alt: "The Catcher in the Rye book",
      price: 13.99,
      brand: "Little, Brown and Company",
      rating: 4.5,
      numReviews: 200,
      countInStock: 10,
      description:
        "J.D. Salinger's iconic novel depicting teenage angst and rebellion.",
    },

    {
      name: "Laptop",
      slug: "laptop",
      category: "Electronics",
      image: "/images/laptop.jpg",
      alt: "Laptop",
      price: 1299.99,
      brand: "Dell",
      rating: 4.6,
      numReviews: 280,
      countInStock: 15,
      description:
        "A high-performance laptop for productivity, gaming, and entertainment.",
    },

    {
      name: "Leather Belt",
      slug: "leather-belt",
      category: "Clothing",
      image: "/images/belt.jpg",
      alt: "Leather belt",
      price: 39.99,
      brand: "Gucci",
      rating: 4.8,
      numReviews: 90,
      countInStock: 25,
      description:
        "A stylish leather belt that adds a touch of sophistication to any outfit.",
    },

    {
      name: "The Alchemist",
      slug: "the-alchemist",
      category: "Books",
      image: "/images/alchemist.jpg",
      alt: "The Alchemist book",
      price: 9.99,
      brand: "HarperOne",
      rating: 4.7,
      numReviews: 400,
      countInStock: 6,
      description:
        "Paulo Coelho's inspirational novel about following one's dreams and destiny.",
    },

    {
      name: "Wireless Speaker",
      slug: "wireless-speaker",
      category: "Electronics",
      image: "/images/speaker.jpg",
      alt: "Wireless speaker",
      price: 149.99,
      brand: "Sonos",
      rating: 4.5,
      numReviews: 190,
      countInStock: 20,
      description:
        "A portable wireless speaker with exceptional sound quality.",
    },

    {
      name: "Running Shoes",
      slug: "running-shoes",
      category: "Clothing",
      image: "/images/shoes.jpg",
      alt: "Running shoes",
      price: 79.99,
      brand: "Nike",
      rating: 4.9,
      numReviews: 150,
      countInStock: 30,
      description:
        "High-performance running shoes designed for comfort and support.",
    },

    {
      name: "The Hobbit",
      slug: "the-hobbit",
      category: "Books",
      image: "/images/hobbit.jpg",
      alt: "The Hobbit book",
      price: 15.99,
      brand: "Houghton Mifflin Harcourt",
      rating: 4.8,
      numReviews: 350,
      countInStock: 4,
      description:
        "J.R.R. Tolkien's enchanting prequel to The Lord of the Rings.",
    },

    {
      name: "Smart Watch",
      slug: "smart-watch",
      category: "Electronics",
      image: "/images/smartwatch.jpg",
      alt: "Smart watch",
      price: 199.99,
      brand: "Samsung",
      rating: 4.4,
      numReviews: 220,
      countInStock: 12,
      description:
        "A feature-packed smart watch for tracking fitness and staying connected.",
    },

    {
      name: "Casual Shirt",
      slug: "casual-shirt",
      category: "Clothing",
      image: "/images/shirt.jpg",
      alt: "Casual shirt",
      price: 34.99,
      brand: "Tommy Hilfiger",
      rating: 4.3,
      numReviews: 100,
      countInStock: 20,
      description:
        "A comfortable and versatile casual shirt for everyday wear.",
    },

    {
      name: "Brave New World",
      slug: "brave-new-world",
      category: "Books",
      image: "/images/brave-new-world.jpg",
      alt: "Brave New World book",
      price: 12.99,
      brand: "HarperPerennial",
      rating: 4.6,
      numReviews: 180,
      countInStock: 8,
      description:
        "A dystopian novel by Aldous Huxley depicting a totalitarian society.",
    },

    {
      name: "Bluetooth Earphones",
      slug: "bluetooth-earphones",
      category: "Electronics",
      image: "/images/earphones.jpg",
      alt: "Bluetooth earphones",
      price: 59.99,
      brand: "Jabra",
      rating: 4.2,
      numReviews: 150,
      countInStock: 25,
      description:
        "Wireless earphones with superior sound quality and long battery life.",
    },

    {
      name: "Denim Jeans",
      slug: "denim-jeans",
      category: "Clothing",
      image: "/images/jeans.jpg",
      alt: "Denim jeans",
      price: 49.99,
      brand: "Levi's",
      rating: 4.7,
      numReviews: 120,
      countInStock: 15,
      description:
        "Classic denim jeans with a comfortable fit and timeless style.",
    },

    {
      name: "The Da Vinci Code",
      slug: "the-da-vinci-code",
      category: "Books",
      image: "/images/da-vinci-code.jpg",
      alt: "The Da Vinci Code book",
      price: 13.99,
      brand: "Anchor",
      rating: 4.5,
      numReviews: 200,
      countInStock: 10,
      description:
        "Dan Brown's gripping thriller involving secret societies and hidden codes.",
    },

    {
      name: "Tablet",
      slug: "tablet",
      category: "Electronics",
      image: "https://example.com/tablet.jpg",
      alt: "Tablet",
      price: 499.99,
      brand: "Apple",
      rating: 4.8,
      numReviews: 280,
      countInStock: 15,
      description:
        "A versatile tablet for productivity, entertainment, and creativity.",
    },

    {
      name: "Winter Coat",
      slug: "winter-coat",
      category: "Clothing",
      image: "/images/coat.jpg",
      alt: "Winter coat",
      price: 89.99,
      brand: "The North Face",
      rating: 4.6,
      numReviews: 150,
      countInStock: 12,
      description:
        "A warm and stylish winter coat to keep you cozy in cold weather.",
    },

    {
      name: "The Hunger Games",
      slug: "the-hunger-games",
      category: "Books",
      image: "/images/hunger-games.jpg",
      alt: "The Hunger Games book",
      price: 9.99,
      brand: "Scholastic",
      rating: 4.7,
      numReviews: 400,
      countInStock: 6,
      description:
        "Suzanne Collins' thrilling dystopian novel set in a post-apocalyptic society.",
    },

    {
      name: "Wireless Mouse",
      slug: "wireless-mouse",
      category: "Electronics",
      image: "/images/mouse.jpg",
      alt: "Wireless mouse",
      price: 29.99,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 190,
      countInStock: 20,
      description:
        "A reliable wireless mouse for precise control and comfortable use.",
    },

    {
      name: "Tennis Shoes",
      slug: "tennis-shoes",
      category: "Clothing",
      image: "/images/tennis-shoes.jpg",
      alt: "Tennis shoes",
      price: 69.99,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 150,
      countInStock: 30,
      description:
        "Durable and supportive tennis shoes for sports and athletic activities.",
    },

    {
      name: "The Chronicles of Narnia",
      slug: "the-chronicles-of-narnia",
      category: "Books",
      image: "/images/narnia.jpg",
      alt: "The Chronicles of Narnia book",
      price: 19.99,
      brand: "HarperCollins",
      rating: 4.8,
      numReviews: 350,
      countInStock: 4,
      description:
        "C.S. Lewis' beloved fantasy series set in the magical world of Narnia.",
    },

    {
      name: "Digital Camera",
      slug: "digital-camera",
      category: "Electronics",
      image: "/images/camera.jpg",
      alt: "Digital camera",
      price: 599.99,
      brand: "Canon",
      rating: 4.4,
      numReviews: 220,
      countInStock: 12,
      description:
        "A high-quality digital camera for capturing stunning photos and videos.",
    },

    {
      name: "Knit Sweater",
      slug: "knit-sweater",
      category: "Clothing",
      image: "/images/sweater.jpg",
      alt: "Knit sweater",
      price: 59.99,
      brand: "H&M",
      rating: 4.3,
      numReviews: 100,
      countInStock: 20,
      description: "A cozy and stylish knit sweater for chilly days.",
    },

    {
      name: "To Kill a Mockingbird",
      slug: "to-kill-a-mockingbird",
      category: "Books",
      image: "/images/mockingbird.jpg",
      alt: "To Kill a Mockingbird book",
      price: 11.99,
      brand: "Harper Lee",
      rating: 4.6,
      numReviews: 180,
      countInStock: 8,
      description:
        "Harper Lee's classic novel addressing racial injustice and morality.",
    },

    {
      name: "Headphones",
      slug: "headphones",
      category: "Electronics",
      image: "/images/headphones.jpg",
      alt: "Headphones",
      price: 149.99,
      brand: "Bose",
      rating: 4.2,
      numReviews: 150,
      countInStock: 25,
      description:
        "High-quality headphones with immersive sound and noise-canceling technology.",
    },

    {
      name: "Formal Dress",
      slug: "formal-dress",
      category: "Clothing",
      image: "/images/formal-dress.jpg",
      alt: "Formal dress",
      price: 99.99,
      brand: "Ralph Lauren",
      rating: 4.7,
      numReviews: 120,
      countInStock: 15,
      description:
        "An elegant and sophisticated formal dress for special occasions.",
    },

    {
      name: "The Great Gatsby",
      slug: "the-great-gatsby",
      category: "Books",
      image: "/images/great-gatsby.jpg",
      alt: "The Great Gatsby book",
      price: 10.99,
      brand: "Scribner",
      rating: 4.5,
      numReviews: 200,
      countInStock: 10,
      description:
        "F. Scott Fitzgerald's iconic novel portraying the Jazz Age and the American Dream.",
    },

    {
      name: "Smart TV",
      slug: "smart-tv",
      category: "Electronics",
      image: "/images/tv.jpg",
      alt: "Smart TV",
      price: 999.99,
      brand: "Samsung",
      rating: 4.8,
      numReviews: 280,
      countInStock: 15,
      description:
        "A feature-rich smart TV with a vibrant display and streaming capabilities.",
    },

    {
      name: "Swimwear",
      slug: "swimwear",
      category: "Clothing",
      image: "/images/swimwear.jpg",
      alt: "Swimwear",
      price: 49.99,
      brand: "Speedo",
      rating: 4.6,
      numReviews: 150,
      countInStock: 12,
      description:
        "Stylish and comfortable swimwear for beach and pool activities.",
    },

    {
      name: "1984",
      slug: "1984",
      category: "Books",
      image: "/images/1984.jpg",
      alt: "1984 book",
      price: 9.99,
      brand: "Signet Classics",
      rating: 4.7,
      numReviews: 400,
      countInStock: 6,
      description:
        "George Orwell's dystopian masterpiece depicting a totalitarian regime.",
    },

    {
      name: "Wireless Keyboard",
      slug: "wireless-keyboard",
      category: "Electronics",
      image: "/images/keyboard.jpg",
      alt: "Wireless keyboard",
      price: 49.99,
      brand: "Logitech",
      rating: 4.5,
      numReviews: 190,
      countInStock: 20,
      description:
        "A sleek and responsive wireless keyboard for comfortable typing.",
    },

    {
      name: "Hoodie",
      slug: "hoodie",
      category: "Clothing",
      image: "/images/hoodie.jpg",
      alt: "Hoodie",
      price: 39.99,
      brand: "Nike",
      rating: 4.9,
      numReviews: 150,
      countInStock: 30,
      description: "A cozy and stylish hoodie for casual and sporty looks.",
    },

    {
      name: "The Lord of the Rings",
      slug: "the-lord-of-the-rings",
      category: "Books",
      image: "/images/lotr.jpg",
      alt: "The Lord of the Rings book",
      price: 29.99,
      brand: "Mariner Books",
      rating: 4.8,
      numReviews: 350,
      countInStock: 4,
      description:
        "J.R.R. Tolkien's epic fantasy trilogy set in the world of Middle-earth.",
    },

    {
      name: "Portable Charger",
      slug: "portable-charger",
      category: "Electronics",
      image: "/images/charger.jpg",
      alt: "Portable charger",
      price: 29.99,
      brand: "Anker",
      rating: 4.4,
      numReviews: 220,
      countInStock: 12,
      description:
        "A compact and high-capacity portable charger for charging devices on the go.",
    },

    {
      name: "Sweatpants",
      slug: "sweatpants",
      category: "Clothing",
      image: "/images/sweatpants.jpg",
      alt: "Sweatpants",
      price: 29.99,
      brand: "Champion",
      rating: 4.3,
      numReviews: 100,
      countInStock: 20,
      description:
        "Comfortable and relaxed sweatpants for lounging or casual activities.",
    },
  ],
};

export default data;
